#!/usr/bin/env ruby
require 'require_all'
require_relative '../lib/environment'

###testing conditions###


###end testing conditions###

Scraper.msnbc_homepage
Scraper.fox_homepage
Scraper.reuters_homepage

CLI.new.call
